version: '3'

services:
  mysql:
    image: mysql:8.0.25
    platform: linux/amd64
    hostname: todo_api
    container_name: todo_api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: company 
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
    ports:
      - "33306:3306" 
