version: '3'

services:
  # mysql:
  #   image: mysql:8.0.25
  #   platform: linux/amd64
  #   hostname: todo_api
  #   container_name: todo_api
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: company 
  #     MYSQL_USER: user 
  #     MYSQL_PASSWORD: password 
  #   ports:
  #     - "33306:3306" 

  mysql:
    image: mysql:8.0.25
    platform: linux/amd64
    hostname: plusone2
    container_name: plusone2
    ports:
      - "13306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true" # 비밀번호 무시
    network_mode: "host"
    restart: always      
